In [2]:
import numpy as np

## 9.4. Операции с массивами
В NumPy над массивами можно производить все старндартные арифметические операции

In [3]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2

print('Сумма: {}\nРазность:{}\nПроизведение:{}\nЧастное:{}\nУмножение на число:{}'.format(result1,result2,result3,result4, result5))

Сумма: [15 21 27]
Разность:[9 9 9]
Произведение:[ 36  90 162]
Частное:[0.25 0.4  0.5 ]
Умножение на число:[ 6 12 18]


### Унивесальные фукнции
Универсальными называют функции, которые выполняют поэлементные операции над данными, хранящимися в объектах ndarray. Большинство универсальных функций относятся к унарным операциям и выполняются над каждым элементом массива по очреди. Унарные операции - это и есть операции, которые выполняются над каждым элментом массива по очереди

Расмотрим список часто используемых универсальных фукнций NumPy. При вызове каждой из этих функци необходимо указаывать название библилотеки NumPy: np.isnan(имя массива):
abs - Абсолютное значение целых, вещественных иликомплексных элементов массива
sqrt - Квадртный корень каждого элемента массива
exp - экспонента каждого элемента масссива
log, log10, log2, log1p - Натуральный (по основанию е), десятичный, двоичный логорифм и фукнция log(1+x)                            соответственно
modf - Дробные и целые части массива в виде отдельных массивов
isnan - массив логических (булевых) значений, показывающий, какие из элементов исходного массива являются           NaN (не числами)
cos,sin,tan - обычные тригонометрические функции
arcos,arcsin,arctan - обратные тригонометрические функции

### Изменение размерности массива

In [4]:
my_array = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(my_array)
my_array.T

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

Дле превращения массива одной размерности в массив другой - обычной для преобразования одномерного массива в многомерный - используется метод reshape. Изменить размерность массива можно только в том случае, если числов элментнов в исходной и в целевом массиве совпадает

In [5]:
my_array = np.random.randint(0,10,20)
print(my_array)
my_array.reshape((4,5))

[5 3 2 1 1 8 9 0 7 0 6 7 6 8 5 2 8 6 6 9]


array([[5, 3, 2, 1, 1],
       [8, 9, 0, 7, 0],
       [6, 7, 6, 8, 5],
       [2, 8, 6, 6, 9]])

ДЛя преобразования многомерного массива в одномерный используется **метод flatten**

In [6]:
my_array = np.array([[1,2,3],[11,22,33],[111,222,333]])
print(my_array)

my_array.flatten()

[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]


array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

### Сравнение и маски

In [7]:
my_array = np.random.randint(0,10,(3,4))
print(my_array)

print('===')
print(my_array < 5)

print('===')
print(my_array[my_array < 5])

[[8 7 1 9]
 [0 1 0 6]
 [2 5 1 5]]
===
[[False False  True False]
 [ True  True  True False]
 [ True False  True False]]
===
[1 0 1 0 2 1]


Маска нжуна для вбора только определенных строк или столбцов из всего массива и скрытия остальных. Маска в Python задается при помощи булевых 0 и 1, где 0 скрывает столбец или строку, а 1 оставляет ее на виду 

In [8]:
print('===')
mask = np.array([1,0,1,0], dtype=bool)
print(my_array[:,mask])

===
[[8 1]
 [0 0]
 [2 1]]


In [9]:
print('ddd')

ddd
