In [4]:
import numpy as np

# 9.2. О массивах NumPy

### Создание массива

In [13]:
arr1 = np.array([5,6,7,8])

print(arr1)

print('=====')

arr2 = np.array([5,6,7,8],dtype=float)

print(arr2.dtype)

print('=====')

# Bivariate array
arr3 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr3.shape)
print(np.shape(arr3))

print('=====')

[5 6 7 8]
=====
float64
=====
(3, 3)
(3, 3)
=====


### Массив из Pandas

В процессе анализа данных возникают ситуации, когда требуется выполнить с данными, хранящимися в Pandas DataFrame, сложные математичесеки операции. Мы можем преобразовать датафрейм или его часть, содержащую количественные показатели, в объект ndarray спомощью функции values библиотеки Pandas

In [18]:
import pandas as pd

df = pd.DataFrame()
x = df.values

print(type(x))

print('=====')

<class 'numpy.ndarray'>
=====


Используя функцию values, массив можно получить из Series

In [19]:
my_series = pd.Series([5,6,7,8,9,10])

print(my_series.values)

[ 5  6  7  8  9 10]


### Другие способы создания массива
Иногда при решении задач нужно создать массив заданноой структуры до того, как становится известно о хранящихся в нем данных. В NumPy есть функции, которые позволяют задвать размерность массива, выделять память для его хранения и заполнять массив элементами (единицамиб нулями)

In [29]:
# одномерный массив из пяти элементов, память для которого выделен, но не инициализирована
np.empty(5)
# Массив размером 10х7, заполненный нулями
np.zeros((10,7))
# Массив размером 3х3х3, заполненный единицами
np.ones((3,3,3))
# единичная матрица (элементы главной диагонали равны 1, остальные - 0) размера 3х3
np.eye(3)
# массив 3х5 заполенный числом 3.14
np.full((3,5),3.14)
# одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7
np.arange(0,21,7)
# массив из пяти чисел, равномерно рапределенных в интервале между 0 и 1 включительно
np.linspace(0,1,5)
# массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)
np.random.randint(0,10, (3,3))

array([[5, 4, 7],
       [1, 4, 6],
       [7, 9, 6]])

### Задание 3

In [35]:
my_secret = [x for x in range(1,301,7) if x%10==7 or x%10 == 1]
print(my_secret)
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

[1, 57, 71, 127, 141, 197, 211, 267, 281]


array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])