
Стили
<!-- Стили -->
<style>
    * {
        font-size:16px
    }
    .f-16px{font-size:16px}
</style>

In [25]:
import numpy as np

## 9.5. **Математические и статистические операции**

In [26]:
students = np.array([
                [1,135,34,4],
                [2,160,43,5],
                [3,163,40,4.3],
                [4,147,44,5],
                [5,138,41,4.7],
                [6,149,54,3.9],
                [7,136,39,4.2],
                [8,154,48,4.9],
                [9,137,35,3.7],
                [10,165,60,4.6],
            ],dtype=float)

students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

### **Средние величины**
**Среднее арифметическое (mean)** - сумма всех значений, деленная на их количество, показывает общую тенденцию данных и описывает их одним числом.

In [27]:
mean = np.mean(students[:,-1])
mean

4.430000000000001

**Медиана** - это такое число, что равно половина элементов из выборки больше него, а другая половина меньше него.
Если в выборке есть выбросы (значения, которые принимаю величину существенно выше или ниже седнего и выделяются из всей выборки),
то медиана будет лучше характеризовать всю выборку, чем среднее арифметическое

In [28]:
median = np.median(students[:,-1])
print(f'Медиана {median}')

sort=np.sort(students[:,-1])
(sort[4]+sort[5])/2

Медиана 4.449999999999999


4.449999999999999

### **Задание 1**
Чему равно медианное значение массы тела школьников

In [38]:
np.median(students[:,2])

42.0

### **Задание 2**
На сколько среднее арифметическое массы тела школьников больше медианного занчения для этого же показателя

In [40]:
mMas = np.median(students[:,2])
meanMas = np.mean(students[:,2])

round(meanMas - mMas,1)

1.8

### **Коэффициент корреляции**
Корреляция - статистическая взаимосвязь случайных величин.
Мерой корреляции служит одноименный коэффициент, который показывает, насколько сильно связаны величины, он может быть положительным или отрицательным, а по модулю принимает значение от 0 до 1. Отрицательный коэффициент говорит о том, что случайные величины связаны, но при увеличении одной из них вторая уменьшается. Если коэффициент положительный, то величины изменяются в одном направлении.

In [41]:
corr = np.corrcoef(students[:,1],students[:,2])
corr

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

## **Задание 3**
Между какой парой признаков в массиве students наблюдается минимальная корреляция, из предложенных вариантов

In [44]:
corGrowMas = np.corrcoef(students[:,1], students[:,2])
corGrowPer = np.corrcoef(students[:,1],students[:,3])
corMasPer = np.corrcoef(students[:,2], students[:,3])

print('Между ростом и массой',corGrowMas)
print('Между ростом и успеваемостью',corGrowPer)
print('Между массой тела и успеваемостью',corMasPer)

Между ростом и массой [[1.         0.64314431]
 [0.64314431 1.        ]]
Между ростом и успеваемостью [[1.         0.46293714]
 [0.46293714 1.        ]]
Между массой тела и успеваемостью [[1.         0.29801325]
 [0.29801325 1.        ]]


<h2><b>Показатели вариации</b></h2>
<p><b>Математическое ожидание</b> - среднее значение случайной величины при стремлении числа ее измерений к <b>бесконечности</b>.
Если число измерений конечно, то для оценки среднего значения величины используется среднее арифметическое</p>
<h3>
<b>Дисперсия</b> - мера разброса случайной величины относительно ее математического ожидания.
</h3>
<p>
<b>D[X] = M[(X - M[X])<sup>2</sup>]</b>
</p>
<p class="f-16px">Дисперсия случайно величины Х равна математическому ожиданию квадрата отклонения случайной величины от ее математического ожидания. То есть, если величина дисперсии небольшая, значит, все числа в выборке имеют близкие друг к другу значения, а чем она больше - тем значительнее разброс показателей</p>

<p><b>Стандартное отклонение</b> - самый распространенный показатель рассеивания случайной величины относительно ее математического ожидания</p>
<p><b>q = ^D[X]</b></p>
<p>Стандартное отклонение равно квадратному корню из дисперсии. Низкое стандартное отклонение показывает, что все значения в выборке сгруппированы около среднего значения. Большой показатель этой величины говорит о том, что разброс значений большой</p>

In [45]:
std = np.std(students[:,1])
std

11.083320801997928

<h2>Задание 4</h2>
<p>Используя имеющийся набор данных о школьниках, найти, чему равно стандартное отклонение их средних баллов</p>

In [46]:
stdNum = np.std(students[:,3])
stdNum

0.4517742799230607

<h2>Задание 5</h2>
<p>Посчитайте, чему равна дисперсия значений веса школьников</p>
<h3>1 Способ</h3>

In [53]:
np.std(students[:,2])**2

60.36

<h3>2 способ</h3>

In [56]:
np.std(students[:,2],ddof=1)

8.189424074174365

In [59]:
type(students)
np.random.randint(1,10, (10,10))

array([[4, 3, 1, 3, 7, 4, 9, 3, 3, 8],
       [7, 2, 8, 2, 9, 1, 9, 3, 2, 1],
       [9, 8, 2, 2, 6, 2, 8, 9, 7, 4],
       [9, 6, 5, 5, 7, 2, 4, 9, 9, 6],
       [9, 2, 7, 4, 9, 8, 7, 9, 4, 5],
       [2, 4, 1, 9, 2, 8, 1, 6, 7, 5],
       [1, 5, 4, 4, 6, 4, 7, 1, 9, 6],
       [7, 1, 9, 7, 5, 5, 9, 9, 8, 3],
       [9, 7, 5, 2, 1, 1, 3, 4, 7, 3],
       [4, 8, 9, 2, 8, 6, 3, 8, 5, 6]])

In [71]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]]);
print(my_array)
print('===')
print(my_array[1:4,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
===
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


<h3><b>Задание 5</b></h3>

In [80]:
my_sin = np.sin(my_array)
round(my_sin.sum(),3)

-0.058

<h2><b>Задание 6</b></h2>

In [88]:
#np.ones(())
my_sin[1:4,1:4] = np.ones_like(my_sin[1:4,1:4])
round(my_sin.sum(),3)

7.572

<h2><b>Задание 7</b></h2>
Преобразовать первые четыре столбца массива my_sin в массива из 10 строк и 2 столбцов. Чему равна сумма элементов первого столбца получившегося массива

In [96]:
round(my_sin[:,0:4].reshape((10,2))[:,0].sum(),3)

2.406

<h3>Подготовка массива к заданию 8-10</h3>
<p>Создайте <b>массив bigdata</b>, содержащий квадраты всех нечетных чисел в диапазоне от 100 до 1000</p>

In [104]:
bigdata = np.array([x**2 for x in range(100,1000) if x%2==1])
bigdata

array([ 10201,  10609,  11025,  11449,  11881,  12321,  12769,  13225,
        13689,  14161,  14641,  15129,  15625,  16129,  16641,  17161,
        17689,  18225,  18769,  19321,  19881,  20449,  21025,  21609,
        22201,  22801,  23409,  24025,  24649,  25281,  25921,  26569,
        27225,  27889,  28561,  29241,  29929,  30625,  31329,  32041,
        32761,  33489,  34225,  34969,  35721,  36481,  37249,  38025,
        38809,  39601,  40401,  41209,  42025,  42849,  43681,  44521,
        45369,  46225,  47089,  47961,  48841,  49729,  50625,  51529,
        52441,  53361,  54289,  55225,  56169,  57121,  58081,  59049,
        60025,  61009,  62001,  63001,  64009,  65025,  66049,  67081,
        68121,  69169,  70225,  71289,  72361,  73441,  74529,  75625,
        76729,  77841,  78961,  80089,  81225,  82369,  83521,  84681,
        85849,  87025,  88209,  89401,  90601,  91809,  93025,  94249,
        95481,  96721,  97969,  99225, 100489, 101761, 103041, 104329,
      

<h3><b>Задание 8</b></h3>
<p>Чему равна медиана массива bigdata</p>

In [105]:
np.median(bigdata)

302501.0

<h3><b>Задание 9</b></h3>
<p>Чему равно стандартное отклонение для массива bigdata?</p>

In [106]:
round(np.std(bigdata))

292095

<h3><b>Задание 10</b></h3>
<p>Чему равен коэффициент корреляции между элементами массива bigdata с четными и нечетными индексами?</p>

In [155]:
np.corrcoef(bigdata[0::2],bigdata[1::2])

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])