In [2]:
import numpy as np

## 9.3. Индексироваие массивов NumPy
Массивы, как и другие итерируемые объекты Python, позволяют обращаться к отдельным своим элементам с помощью индексов и срезов. В этом разделем мы рассмотрим некоторые особенности индексации масиивов разаной размерности. При работе с одномерными массивами все пр иемы работы с индексами похожи на приемы при работе со списками

In [8]:
my_array = np.array([x for x in range(10)])
print(my_array[5])
print(my_array[-1])
print(my_array[3:6])
print(my_array[1:8:3])

5
9
[3 4 5]
[1 4 7]


При работе с двумерными массивами для обращения к элементу мы указваем два индекса, соответствующие номеру строки и номеру столбца. Каждый индекс можно указывать в отдельных квадратных скобках или внутри одной пары скобок через запятую

In [10]:
my_array = np.array([
    [1,2,3,4],
    [10,11,12,13],
    [45,46,47,48]
])

print(my_array[1][2])
print(my_array[1,2])

12
12


### Индексация двумерных массивов имеет следующие особенности
- при указании только одного оиндекса из массива будет выделена вся строка, соответствующая указанному индексу
- можно указывать несколько индексов или срезов для каждой из осей 

In [15]:
print(my_array[1])
print(my_array[:,2])
print(my_array[1:,1:3])

[10 11 12 13]
[ 3 12 47]
[[11 12]
 [46 47]]


## Упражнения

In [37]:
first_line = [x*y for x in range(2,100,6) for y in range(7,1,-2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x ** 2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

## Задание 1

In [38]:
sum_last_column = 0
index_column = big_secret.shape[1] - 1

for k in range(big_secret.shape[0]):
    sum_last_column += big_secret[k][index_column]

print(f'Сумма элементов последнего стобца массива {round(sum_last_column,2)}')

Сумма элементов последнего стобца массива 3154.33


## Задание 2

In [66]:
five_row_big = big_secret[:5, :5]
sum_diagonal = 0

for k in range(five_row_big.shape[0]):
    sum_diagonal += five_row_big[k][k]

print(f'Сумма элементов главной диагонали матрицы {round(sum_diagonal,2)}')

Сумма элементов главной диагонали матрицы 121.37


## Задание 3

In [93]:
row_five_last_element = big_secret[:5, -5:]
multiply_diagonal = 1

#print(row_five_last_element.shape)

for k in range(row_five_last_element.shape[0]):
    #print(row_five_last_element[k][k])
    multiply_diagonal *= row_five_last_element[k][k]

#print(row_five_last_element)
print(multiply_diagonal)

341505315559.2347


## Особенности индексирования
Важное отличие массивов NumPy от списков Python - при изменении среза или отдельных элементов все изменения касаются не только самого среза, но и падают в исходный массив, даже если перед внесением изменений срез был сохранен в виде отдельной переменной

In [102]:
my_array = np.random.randint(1,100, (4,6))

print(my_array)
print('===')

my_slice = my_array[1:3, 2:4]

print(my_slice)
print('===')

my_slice[:] = 0

print(my_array)

[[ 9 26 47 27 64  4]
 [77 50 84 81  6 18]
 [ 5 22 51 29 82 86]
 [25 69 56  2 17 68]]
===
[[84 81]
 [51 29]]
===
[[ 9 26 47 27 64  4]
 [77 50  0  0  6 18]
 [ 5 22  0  0 82 86]
 [25 69 56  2 17 68]]


## Упражнения
Замените на 1 все элементы, у которых оба индекса нечетные, и на -1 все элементы, у которых обо индекса нечетные

In [112]:

for i in range(big_secret.shape[0]):
    for j in range(big_secret.shape[1]):
        if ((i+1)%2) and ((j+1)%2):
            big_secret[i][j] = -1
        elif not ((i+1)%2) and not ((j+1)%2):
            big_secret[i][j] = 1

## Задание 4

In [113]:
row_five_element = big_secret[:5, :5]

five_diagonal = 0

for k in range(row_five_last_element.shape[0]):
    five_diagonal += row_five_last_element[k][k]

print(five_diagonal)

-1.0


## Задание 5

In [114]:
row_five_element_last = big_secret[:5,-5:]
multiply_diag_five = 1
for k in range(row_five_element_last.shape[0]):
    multiply_diag_five *= row_five_element_last[k][k]

print(multiply_diag_five)

-1.0
