## 9.4 Операции с массивами
### Операции с массивами

In [62]:
import numpy as np

In [63]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2

print('Сумма: {}\nРазность:{}\nПроизведение:{}\nЧасное:{}\nУмножение на число:{}'.format(result1,result2,result3,result4,result5))

Сумма: [15 21 27]
Разность:[9 9 9]
Произведение:[ 36  90 162]
Часное:[0.25 0.4  0.5 ]
Умножение на число:[ 6 12 18]


### Изменение размерности массива

In [64]:
my_array = np.array([[1,2,3,4,5],[6,7,8,9,10]])
my_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

Для **превращения** массива одной **размерности** в массив другой -
обычно для преобразования одномерного массива в многомерный -
используется **метод reshape**

In [65]:
my_array = np.random.randint(0,10,20)
my_array.reshape((4,5))

array([[5, 7, 0, 1, 2],
       [0, 9, 2, 3, 1],
       [7, 5, 3, 5, 9],
       [3, 3, 5, 9, 6]])

Для преобразования многомерного массива в одномерный используется **метод flatten**

In [66]:
my_array = np.array([[1,2,3],[11,22,33],[111,222,333]])
my_array.flatten()

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

### **Сравнение и маски**

In [67]:
my_array = np.random.randint(0,10,(3,4))
my_array<5

array([[False,  True, False,  True],
       [False,  True, False, False],
       [ True,  True, False,  True]])

In [68]:
my_array[my_array<5]

array([4, 2, 2, 2, 2, 2])

**Маска** нужна для **выбора** только определенных строк или столбцов из всего массива и скрытия остальных.

Маска в Python задается при помощи булевых 0 и 1, где 0 скрывает столбец или строку, а 1 оставляет ее на виду.

In [76]:
mask = np.array([1,0,0,0], dtype=bool)
print(my_array)
my_array[mask]

[[8 2 8 5 1 1]
 [0 6 8 7 5 4]
 [7 6 9 6 7 8]
 [5 5 3 2 5 9]]


array([[8, 2, 8, 5, 1, 1]])

### **Сортировка двумерных массивов**
Сортировка выполняется с помощью **функции sort**, в качестве параметров функция получает сам массив, а также номер оси (0 - для столбцов или 1 - для строк),

In [70]:
my_array = np.random.randint(0,10,(4,6))
np.sort(my_array,axis=1)
np.sort(my_array,axis=0)

array([[0, 2, 3, 2, 1, 1],
       [5, 5, 8, 5, 5, 4],
       [7, 6, 8, 6, 5, 8],
       [8, 6, 9, 7, 7, 9]])

## **Упраженения**

In [71]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100,200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first,second,third]).T

### **Задание 1**
Сколько столбцов содержит массива great_secret

In [72]:
great_secret

array([[ 0.        ,  4.64158883, 66.66666667],
       [ 1.        ,  4.65700951, 40.        ],
       [ 1.41421356,  4.67232873, 67.33333333],
       [ 1.73205081,  4.68754815, 40.4       ],
       [ 2.        ,  4.70266938, 68.        ],
       [ 2.23606798,  4.71769398, 40.8       ],
       [ 2.44948974,  4.73262349, 68.66666667],
       [ 2.64575131,  4.7474594 , 41.2       ],
       [ 2.82842712,  4.76220316, 69.33333333],
       [ 3.        ,  4.77685618, 41.6       ],
       [ 3.16227766,  4.79141986, 70.        ],
       [ 3.31662479,  4.80589553, 42.        ],
       [ 3.46410162,  4.82028453, 70.66666667],
       [ 3.60555128,  4.83458813, 42.4       ],
       [ 3.74165739,  4.84880759, 71.33333333],
       [ 3.87298335,  4.86294413, 42.8       ],
       [ 4.        ,  4.87699896, 72.        ],
       [ 4.12310563,  4.89097325, 43.2       ],
       [ 4.24264069,  4.90486813, 72.66666667],
       [ 4.35889894,  4.91868473, 43.6       ],
       [ 4.47213595,  4.93242415, 73.333

### **Задание 2**
Чему равна сумма косинусов элементов первой сроки массива great_secret

In [81]:
#mask_2 = np.array()
#arr_2 =
# 
round(np.cos(great_secret[0]).sum(),2)

0.16

### **Задание 3**
Чему равна сумма элементов массива great_secret, значение которых больше 50

In [82]:
great_secret[great_secret>50].sum()

5470.0

### Задание 4
Переведите массив great_secret в одномерную форму. Какое значение в получившемся масссиве имеет элемент с индексом 150

In [85]:
great_secret.flatten()[150]

7.0710678118654755

### Задание 5
Отсортируйте значения столбцов массива great_secret по возрастанию. Чему равна сумма элементов последней строки отсортированного массива

In [91]:
round(np.sort(great_secret,axis=0)[-1].sum(),2)

115.12148016521353